# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-07 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_notice_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='是否显示'),
        ),
    ]
