# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-09 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_notice_is_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='article',
        ),
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='评论者名字'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.CharField(default='', max_length=200, verbose_name='评论'),
        ),
    ]
