# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190309_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
