# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20190310_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_show',
            field=models.CharField(choices=[(1, '展示'), (2, '不展示')], default=2, max_length=30, verbose_name='是否展示'),
        ),
    ]
