# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20190312_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_show',
            field=models.CharField(choices=[(1, '展示'), (2, '不展示')], default=2, max_length=20, verbose_name='是否展示'),
        ),
    ]
